microService:
  # 本地监听商品，docker中
  port: 9999
  # 本地监听主机，docker中
  host: 0.0.0.0
etcd:
  hosts:
    - "192.168.0.201:12379"
  options:
    cert:          ""
    key:           ""
    caCert:        ""
    dialTimeout:   30
    dialKeepAlive: 30
    username:      ""
    password:      ""
postgres:
  url:  "host=192.168.0.201 user=root dbname=test sslmode=disable password=password"
  poolMax: 100
  poolMin:  10
redis:
  addrs:
    - "192.168.0.201:7001"
    - "192.168.0.201:7002"
    - "192.168.0.201:7003"
    - "192.168.0.201:7004"
    - "192.168.0.201:7005"
    - "192.168.0.201:7006"
  password: ""
  poolSize: 100
  minIdleConns: 10
emq:
  url: ""
  host: "192.168.0.201"
  tcpPort: "1883"
  userName: ""
  password: ""

mongo:
  url:  "mongodb://root:password@192.168.0.201:27017/test?&authSource=admin"
  options:
    connectTimeout: 10
    heartbeatInterval: 20
    maxConnIdleTime:   300
    maxPoolSize:       100
    minPoolSize:       10
    serverSelectionTimeout: 5

