# 這個段的微服是不同的
microService:
  # 每一种服务不相同，同类的微服务相同
  tag:  api
  # 本地监听商品，docker中
  port: 9001
  # 本地监听主机，docker中
  host: localhost
  # etct注册端口，docker映射到外部时使用
  regPort: 9001
  # etct注册主机，docker映射到外部时使用
  regHost: localhost
# 所有微服務相同
etcd:
  hosts:
    - "192.168.0.99:2379"
  options:
    cert:          ""
    key:           ""
    caCert:        ""
    # dialTimeout:   30
    # dialKeepAlive: 30
    username:      ""
    password:      ""
# 所有微服務可能相同
postgres:
  url:  "host=127.0.0.1 user=root dbname=test sslmode=disable password=password"
  poolMax: 100
  poolMin:  10
# 所有微服務相同
redis:
  addrs:
    - "192.168.0.99:7001"
    - "192.168.0.99:7002"
    - "192.168.0.99:7003"
    - "192.168.0.99:7004"
    - "192.168.0.99:7005"
    - "192.168.0.99:7006"
  password: ""
  poolSize: 100
  minIdleConns: 10
# 所有微服務相同
emq:
  url: ""
  host: "192.168.0.99"
  tcpPort: "1883"
  userName: ""
  password: ""
# 所有微服務相同
mongo:
  #url:  "mongodb://root:password@172.2.2.2:27017/test?&authSource=admin"
  url:  "mongodb://root:password@192.168.0.99:27017/test?&authSource=admin"
  options:
    connectTimeout: 10
    heartbeatInterval: 20
    maxConnIdleTime:   300
    maxPoolSize:       100
    minPoolSize:       10
    serverSelectionTimeout: 5
